services:
  dokploy:
    image: dokploy/dokploy:latest
    container_name: dokploy
    restart: always
    ports:
      - "8090:3000"
    environment:
      - DATABASE_URL=postgresql://dokploy:dokploy@dokploy-postgres:5432/dokploy
      - REDIS_HOST=dokploy-redis
      - REDIS_PORT=6379
      - DOKPLOY_DISABLE_SWARM=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dokploy_data:/etc/dokploy
    depends_on:
      - dokploy-postgres
      - dokploy-redis

  dokploy-postgres:
    image: postgres:15
    container_name: dokploy-postgres
    restart: always
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: dokploy
      POSTGRES_DB: dokploy
    command: ["postgres", "-c", "listen_addresses=*"]
    ports:
      - "5433:5432"
    volumes:
      - dokploy_postgres_data:/var/lib/postgresql/data

  dokploy-redis:
    image: redis:7
    container_name: dokploy-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - dokploy_redis_data:/data

volumes:
  dokploy_data:
  dokploy_postgres_data:
  dokploy_redis_data:
