FROM node:22-alpine as build

WORKDIR /usr/src/app

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY app/frontend/package*.json ./
RUN npm install

COPY app/frontend ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
